apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
        name: yogicluster
        region: ap-south-1
nodeGroups:
        - name: ng1
          desiredCapacity: 3
          instanceType: t2.micro
          ssh:
                 publicKeyName: cloudf


        - name: ng-1
          minSize: 2
          maxSize: 5
          instancesDistribution:
             maxPrice: 0.017
             instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
             onDemandBaseCapacity: 0
             onDemandPercentageAboveBaseCapacity: 50
             spotInstancePools: 2
          ssh:
                  publicKeyName: cloudf
